### ISSUE TITLE
increase font size in ADTLink log

### ISSUE THREAD

**Issue by stevebus** [stevebus/unrealdemo#1]
The log in ADT link is pretty small and hard to read..   Can we up the font size?

![image](https://user-images.githubusercontent.com/11857454/121973267-7fc3b500-cd42-11eb-986a-b5cae5155ac3.png)

**Comment by SamWSP** [comment]
Font size updated, around 20% bigger.
![2021-06-15 11_12_00-BP_AdtSetup](https://user-images.githubusercontent.com/76430567/122027258-42573a00-cdcb-11eb-8bd2-2321f44534a1.png)
