### ISSUE TITLE
Access to source code of the function app

### ISSUE THREAD

**Issue by AndersRod** [stevebus/unrealdemo#7]
The function app package is currently hosted [external](https://github.com/stevebus/stuff/raw/main/unrealdemofuncs.zip) to this repo. I imagine this is done in order to keep the deployment process as simple as possible (no need for a build agent, etc). 
Is it possible to get access to the source code, as I am curious to learn more about the IoTHubIngest and broadcast functions?

**Comment by stevebus** [comment]
I just added a 'function-code' folder in this repo and copied the code there.   It's in the form of a VS 2019 project.  It has some old, defunct credentials of mine in the local settings file as examples.
